### ISSUE TITLE
missing entries from DefinitelyTyped

### ISSUE THREAD

**Issue by scttcper** [Microsoft/TypeSearch#16]
It exists https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/koa-logger

but does not come up. Same with other koa- varieties. e.g. koa-send koa-session-minimal

<img width="534" alt="screen shot 2017-01-27 at 3 46 56 pm" src="https://cloud.githubusercontent.com/assets/1400464/22391751/ef5e5aba-e4a7-11e6-823d-bfc6caa9de0b.png">
<img width="553" alt="screen shot 2017-01-27 at 3 47 03 pm" src="https://cloud.githubusercontent.com/assets/1400464/22391752/ef602c5a-e4a7-11e6-85fd-8508848f77c8.png">

**Comment by cheeZery** [comment]
@scttcper it's seems that it's fixed
![image](https://user-images.githubusercontent.com/10416213/47589982-23ca7900-d96b-11e8-83ca-99f7f8a33306.png)
