### ISSUE TITLE
Search totally down?

### ISSUE THREAD

**Issue by mattblackdev** [microsoft/TypeSearch#17]
Failed to load resource: the server responded with a status of 404 (Not Found)
typeahead.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
typeahead.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
(index):14 Uncaught ReferenceError: $ is not defined
    at (index):14

**Comment by onlyutkarsh** [comment]
+1 same issue for me.

**Comment by mdg357** [comment]
Same here

**Comment by mbeauchamp7** [comment]
Looks like <script src="node_modules/jquery/dist/jquery.min.js"></script> isn't there.

Maybe use the cdn?? 
```
<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
```

https://code.jquery.com/

**Comment by rajington** [comment]
Feel free to use https://rajington.github.io/TypeSearch/ until they merge.

**Comment by JoshuaKGoldberg** [comment]
@rajington thanks! :)

**Comment by lgrignon** [comment]
@rajington You are a life saver, thanks :)

**Comment by JoshuaKGoldberg** [comment]
...and it's back up!

**Comment by karlhorky** [comment]
@mattblackdev this can be closed now, right?
