### ISSUE TITLE
Make it work with URL search params

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/TypeSearch#31]
Inspired by this tip:

https://twitter.com/SavePointSam/status/1083145648470290432

I would like to add TypeSearch to Chrome as a search engine. Instead of finding the website (which I always forget the address of), one could type:

```
types ramda
```

or even

```
types ram
```

In order to be presented with either the result (1) or TypeSearch UI with the search field focused in & the partial query already there.

What do you think?

**Comment by himynameisdave** [comment]
Totally second this! 👍
